# Generated by Django 5.2.12 on 2026-04-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="event",
            table="events_event",
        ),
    ]
