# Generated by Django 5.2.12 on 2026-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_date_remove_event_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="sales_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
