# Generated by Django 5.2.12 on 2026-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_tickettype_sales_expiry_date_alter_tickettype_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="nature",
            field=models.CharField(
                blank=True,
                choices=[("Online", "ONLINE"), ("In-Person", "IN_PERSON")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Music", "MUSIC"),
                    ("Sports", "SPORTS"),
                    ("Tech", "TECH"),
                    ("Art", "ART"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
