# Generated by Django 5.2.12 on 2026-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_nature_alter_event_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="nature",
            new_name="type",
        ),
    ]
