# Generated by Django 5.2.12 on 2026-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rename_nature_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("ONLINE", "ONLINE"), ("IN_PERSON", "IN_PERSON")],
                max_length=100,
                null=True,
            ),
        ),
    ]
