# Generated by Django 5.2.12 on 2026-07-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="otp",
            field=models.CharField(max_length=300),
        ),
    ]
