# Generated by Django 5.2.12 on 2026-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailotp_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
