# Generated by Django 5.2.12 on 2026-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verify_existing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRateLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
