# Generated by Django 4.2.28 on 2026-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
