# Generated by Django 4.2.28 on 2026-03-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_active_tickettype_created_at_and_more'),
        ('orders', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.UUIDField(unique=True),
        ),
    ]
