# Generated by Django 4.2.28 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ticket_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(upload_to='ticketQR/'),
        ),
    ]
